name: Build & Deploy repos Site

env:
  SITE_TEMPLATE_PATH: ".github/templates/site"

on:
  workflow_call:
    inputs:
      site_title:
        type: string
        required: false
        default: ""
      execute:
        type: string
        required: false
        default: "false"
      template_repo:
        type: string
        required: false
        default: "High-Energy-Physics-Research/high-energy-physics-research.github.io"
      template_ref:
        type: string
        required: false
        default: "main"

permissions:
  contents: write

concurrency:
  group: "build-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout discipline repo
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Checkout central (template + scripts + registry)
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.template_repo }}
          ref: ${{ inputs.template_ref }}
          path: central
          sparse-checkout: |
            .github/templates
            .github/scripts/build_site.py
            .github/registry
          sparse-checkout-cone-mode: false

      - name: Validate template path
        run: |
          set -euo pipefail
          TEMPLATE_DIR="central/${{ env.SITE_TEMPLATE_PATH }}"
          echo "TEMPLATE_DIR=$TEMPLATE_DIR"
          test -f "$TEMPLATE_DIR/index.html" || { echo "index.html não encontrado em $TEMPLATE_DIR"; ls -laR central; exit 1; }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert jinja2 nbformat pyyaml

      - name: Copy template from central
        run: |
          set -euo pipefail
          rm -rf template
          rsync -a --delete "central/${{ env.SITE_TEMPLATE_PATH }}/" "template/"

      - name: Resolve config from central registry
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import os, sys, yaml
          from pathlib import Path

          full = os.environ.get("GITHUB_REPOSITORY", "")
          if "/" not in full:
            print(f"[fatal] invalid GITHUB_REPOSITORY={full}", file=sys.stderr)
            sys.exit(2)

          owner, repo = full.split("/", 1)

          reg = Path("central/.github/registry/repos.yml")
          if not reg.exists():
            print(f"[fatal] registry not found: {reg}", file=sys.stderr)
            sys.exit(2)

          data = yaml.safe_load(reg.read_text(encoding="utf-8")) or {}
          items = data.get("repos", [])
          if not isinstance(items, list):
            print(f"[fatal] registry key 'repos' must be a list: {reg}", file=sys.stderr)
            sys.exit(2)

          owner_l = owner.lower()
          repo_l  = repo.lower()

          hit = next(
              (
                  it for it in items
                  if (it.get("org", "").lower() == owner_l)
                  and (it.get("name", "").lower() == repo_l)
              ),
              None
          )
          if not hit:
            print(f"[fatal] repo {owner}/{repo} not found in central registry: {reg}", file=sys.stderr)
            sys.exit(2)

          site_url = hit.get("site_url") or f"https://{owner}.github.io/{repo}"

          out = {
            "TITLE": hit.get("title") or repo,
            "HERO_FILE": hit.get("site_hero_image") or "",
            "SUBTITLE": hit.get("site_subtitle") or "",
            "ABOUT": hit.get("site_description") or "",
            "SITE_URL": site_url,
            "GITHUB_URL": f"https://github.com/{owner}/{repo}",
            "GITHUB_LINK": f"https://github.com/{owner}/{repo}"
          }

          Path("_cfg").mkdir(exist_ok=True)
          Path("_cfg/site.yml").write_text(
            yaml.safe_dump(out, sort_keys=False, allow_unicode=True),
            encoding="utf-8"
          )
          print("[ok] wrote _cfg/site.yml")
          PY

      - name: Fetch hero image (from central)
        shell: bash
        run: |
          set -euo pipefail

          HERO_DIR_IN_CENTRAL="img/portfolio"

          BASE_RAW="https://raw.githubusercontent.com/${{ inputs.template_repo }}/${{ inputs.template_ref }}"

          python - <<'PY' > hero_file.txt
          import yaml
          from pathlib import Path
          cfg = yaml.safe_load(Path("_cfg/site.yml").read_text(encoding="utf-8")) or {}
          print((cfg.get("HERO_FILE") or "").strip())
          PY

          HERO_FILE="$(cat hero_file.txt || true)"
          if [ -z "$HERO_FILE" ]; then
            echo "Sem HERO_FILE → pulando download da hero."
            exit 0
          fi

          HERO_URL="$BASE_RAW/$HERO_DIR_IN_CENTRAL/$HERO_FILE"
          echo "Baixando hero: $HERO_URL"

          mkdir -p template/assets/img
          curl -fsSL "$HERO_URL" -o template/assets/img/hero.png
          sed -i.bak 's#{{ *HERO_URL *}}#./assets/img/hero.png#g' template/index.html

      - name: Build site
        run: |
          python central/.github/scripts/build_site.py \
            --src repo \
            --out site \
            --template template \
            --title "${{ inputs.site_title }}" \
            --cfg "_cfg" \
            --execute ${{ inputs.execute }}

      - name: Show site tree
        run: |
          echo "== Conteúdo da pasta site =="
          ls -lah site || true
          echo "== Estrutura de arquivos =="
          find site -maxdepth 3 -type f | sort

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true