# .github/workflows/build-readme.yml
name: Build & Deploy repos README.md (Reusable)

env:
  README_TEMPLATE_PATH: ".github/templates/readme"

on:
  workflow_call:
    inputs:
      template_repo:
        type: string
        required: false
        default: "High-Energy-Physics-Research/high-energy-physics-research.github.io"
      template_ref:
        type: string
        required: false
        default: "main"

permissions:
  contents: write

concurrency:
  group: "readme"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout central templates + scripts + registry
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.template_repo }}
          ref: ${{ inputs.template_ref }}
          path: central
          sparse-checkout: |
            .github/templates/readme
            .github/scripts/build_readme.py
            .github/registry/repos.yml
          sparse-checkout-cone-mode: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # 1) Resolve cfg (readme.yml) from central registry
      - name: Resolve README config from central registry
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import os, sys, yaml
          from pathlib import Path

          full = os.environ.get("GITHUB_REPOSITORY", "")
          if "/" not in full:
            print(f"[fatal] invalid GITHUB_REPOSITORY={full}", file=sys.stderr)
            sys.exit(2)

          owner, repo = full.split("/", 1)

          reg = Path("central/.github/registry/repos.yml")
          data = yaml.safe_load(reg.read_text(encoding="utf-8")) or {}
          items = data.get("repos", [])
          if not isinstance(items, list):
            print(f"[fatal] registry repos must be a list: {reg}", file=sys.stderr)
            sys.exit(2)

          hit = None
          for it in items:
            if (it.get("org") == owner) and (it.get("name") == repo):
              hit = it
              break

          if not hit:
            print(f"[fatal] repo {owner}/{repo} not found in registry: {reg}", file=sys.stderr)
            sys.exit(2)

          # Defaults sensatos (runtime)
          site_url = hit.get("site_url") or f"https://{owner}.github.io/{repo}"
          assets_dir = hit.get("readme_assets_dir") or ".github/readme"

          out = {
            # tokens que seu template do readme costuma usar
            "TITLE": hit.get("title") or repo,                 # opcional (se o template usa)
            "REPO_TAGLINE": hit.get("readme_tagline") or "",
            "CTA_TEXT": hit.get("readme_cta_text") or "Access the full course website",
            "THEME": hit.get("readme_theme") or "coding",
            "SITE_URL": site_url,
            "ASSETS_DIR": assets_dir,
          }

          Path("_cfg").mkdir(exist_ok=True)
          Path("_cfg/readme.yml").write_text(
            yaml.safe_dump(out, sort_keys=False, allow_unicode=True),
            encoding="utf-8"
          )
          print("[ok] wrote _cfg/readme.yml")
          PY

      # 2) Build README + SVGs
      - name: Build README + SVGs
        run: |
          python central/.github/scripts/build_readme.py \
            --repo . \
            --central "central/${{ env.README_TEMPLATE_PATH }}" \
            --repo-cfg "_cfg"

      # 3) Commit changes (if any)
      - name: Commit changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          # adiciona só o que interessa, sem falhar se não existir
          git add README.md || true
          git add .github/readme || true

          git commit -m "Update files"
          git push