name: Listener Update Website

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  run:
    uses: naavilam/github-infra-templates/.github/workflows/manager-provisioner.yml@main
    with:
      org: ${{ vars.org }}