name: Notify Managers Readme Update
run-name: Notify Managers Readme Update

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"